import { SettingsModules } from '@src/types';

export const HOME_PAGE_PATH = '/';
export const DASHBOARD_PAGE_PATH = '/dashboard';
export const REQUESTS_PAGE_PATH = '/requests';
export const REQUEST_DETAILS_PAGE_PATH = '/requests/:id';
export const GARAGE_CUSTOMERS_PAGE_PATH = '/garage-customers';
export const STATS_PAGE_PATH = '/stats';
export const MARKETING_PAGE_PATH = '/marketing';
export const NOTIFICATIONS_PAGE_PATH = '/notifications';
export const SETTINGS_PAGE_PATH = '/settings';
export const NOTIFICATIONS_SETTINGS_PAGE_PATH: SettingsModules = 'notification-settings';
export const COMPANY_INFO_PAGE_PATH: SettingsModules = 'company-info';
export const SYSTEM_USERS_PAGE_PATH: SettingsModules = 'system-users';
export const ACCOUNT_DETAILS_PAGE_PATH: SettingsModules = 'account-details';
export const PRICING_AND_BILLING_PAGE_PATH: SettingsModules = 'pricing-and-billings';
export const LOGIN_PAGE_PATH = '/login';
export const LOGOUT_PAGE_PATH = '/logout';
export const FORGET_PASSWORD_PATH = '/forget-password';
export const RESET_PASSWORD_PAGE_PATH = '/reset-password';
export const NEW_PASSWORD_PAGE_PATH = '/new-password';
export const NOT_FOUND_PAGE_PATH = '*';
export const CAMPAIGNS_PAGE_PATH = '/marketing/campaigns';
